pagehelper:
  helperDialect:  mysql
  reasonable: false
  supportMethodsArguments:  true
  params: count=countSql
spring:
  datasource:
    clickhouse:
      address: jdbc:clickhouse://192.168.1.99:8123
      username:
      password:
      db: default
      socketTimeout: 600000
